.github/workflows/mashed-main.yml, README.md, apilayer/handler/ProfileHandler.go, apilayer/main.go, frontend/src/Components/AddCommunityEvent/AddCommunityEvent.js, frontend/src/Components/AddCommunityEvent/constants.js, frontend/src/Components/AppBar/PrimaryAppBar.js, frontend/src/Components/Auth/Login.js, frontend/src/Components/Event/EventDetailsDrawerComponent.js, frontend/src/Components/HostComponent/Host.js, frontend/src/Components/ItemDetail/AddItemDetail.js, frontend/src/Components/ItemDetail/ViewItemDetail.js, frontend/src/Components/ItemDetail/constants.js, frontend/src/Components/Map/styles.css, frontend/src/Components/Organization/ReportCommunityEvent.js, frontend/src/Components/Organization/SearchAllEvents.js, frontend/src/Components/Organization/constants.js, frontend/src/Components/PieChart/PieChart.js, frontend/src/Components/ViewEventListCta/CreateNewEventCta.js, frontend/src/Components/ViewEventListCta/NavigateProfileFromEventCta.js, frontend/src/Components/ViewEventsListDetails/ViewEventListDetails.js, frontend/src/Containers/Auth/AuthHome.js, frontend/src/Containers/Event/EventDetailPage.js, frontend/src/Containers/Event/constants.js, frontend/src/Containers/Home/HomePage.js, frontend/src/Containers/Home/homeSaga.js, frontend/src/Containers/Home/homeSlice.js, frontend/src/Containers/Profile/ProfileDetailPage.js, frontend/src/Containers/Profile/constants.js
Adds github workflow for smoother dev experience.
Closes #11
=> Add Github workflow to application

frontend/src/Components/Auth/AuthHeroSection.js, frontend/src/Components/Auth/Login.js, frontend/src/Components/Auth/constants.js, frontend/src/Components/DialogComponent/Title.js, frontend/src/Components/RsvpComponent/RSVPRegistration.js
- remove debounce fn because the user feels a lag during the log in submission. the debounce can be used in other places but nothing atm.
- add chrome dev suggestion for pwd field so that chrome can suggest a stronger password.
=> Remove debounce and apply pwd suggestion ability

Makefile, apilayer/db/Eventsdb.go, apilayer/handler/EventHandler_test.go, apilayer/handler/ProfileHandler_test.go
Adding unit test for api layer.
=> Add extra unit test for api layer

apilayer/README.md, apilayer/db/Eventsdb.go, apilayer/db/Notificationsdb.go, apilayer/db/Profiledb.go, apilayer/db/Userdb.go, frontend/README.md, server/README.md
- added tx in all of the put and post endpoints. closes #38
- updates readme closes #45
- closes #39 as no-op since the EmptyComponent renders instead
=> Add tx where required in db. Update readme

.github/workflows/mashed-main.yml, .gitignore, Makefile, server/devscript/test_data.sql
Adding the ability to run unit test for api layer code.
=> add test data for reports

frontend/src/Components/ViewEventsListDetails/ViewFilteredEventList.jsx, frontend/src/Containers/Profile/ProfileDetailPage.jsx
- remove notification state and pull fresh state from redux store.
- add icon for in demand skills to display in the card section of each
event.
- removed unused constants file.
Closes #54
=> Update notifcation state and add icons for in-demand skills

apilayer/db/Profiledb.go, apilayer/model/Profile.go, frontend/src/Components/ProfileNavigationMenu/ProfileNavigationMenu.jsx, frontend/src/Components/ProfileNavigationMenu/constants.jsx, frontend/src/Components/RecentActivitiesList/RecentActivity.jsx, frontend/src/Components/RecentActivitiesList/RecentItemTabs.jsx, frontend/src/Components/ViewEventsListDetails/ViewEventListDetails.jsx, frontend/src/stories/CreateNewEvent/CreateNewEvent.jsx, frontend/src/stories/Login/Login.jsx, frontend/src/stories/NavListItem/AppBarNavListItem.jsx, frontend/src/stories/Signup/Signup.jsx
- Retrives relative projects with user id. if you have created an event or volunteered an event, then it should be displayed on the recent activities list. 
- Add css cleanup and update prop types in the project.
=> Retrieve relative projects with userID

frontend/src/Components/ItemDetail/constants.js, frontend/src/Components/Notes/Notes.jsx, frontend/src/Components/Notes/NotesDetails.jsx, frontend/src/Components/ProfileNavigationMenu/ProfileNavigationMenu.jsx, frontend/src/stories/InviteSection/InviteSection.jsx
- Added the basic ui structure for notes section.
=> Add basic layout for notes section

frontend/src/Components/CommunityEvent/ReportCommunityEvent.jsx, frontend/src/Components/Event/EventDetailsDrawerComponent.jsx, frontend/src/Components/Inventory/Inventories.jsx, frontend/src/Components/Inventory/constants.jsx, frontend/src/Components/ItemDetail/ViewItemDetail.jsx, frontend/src/Components/ProfileNavigationMenu/ProfileNavigationMenu.jsx, frontend/src/Components/ProfileNavigationMenu/constants.jsx, frontend/src/Components/RecentActivitiesList/RecentActivitiesListContainer.jsx, frontend/src/Components/RecentActivitiesList/RecentItemTabs.jsx, frontend/src/Components/RecentActivitiesList/RecentTrophyCollections.jsx
All navbars are now combined in the platform.
=> Combine all navbars across the platform

apilayer/db/Profiledb.go, apilayer/handler/ProfileHandler.go, apilayer/handler/ProfileHandler_test.go, apilayer/main.go, apilayer/model/Profile.go, frontend/src/Components/ItemDetail/AddItemDetail.jsx, frontend/src/Components/ItemDetail/ViewItemDetail.jsx, frontend/src/Components/Notes/AddNote.jsx, frontend/src/Components/Notes/Notes.jsx, frontend/src/Components/Notes/NotesDetails.jsx, frontend/src/Components/Notes/constants.jsx, frontend/src/Components/ViewExpenseList/AddExpenseDetail.jsx, frontend/src/Containers/Profile/profileSaga.js, frontend/src/Containers/Profile/profileSlice.js, server/migrations/0023_add_notes_section_profile_page.up.sql
- added api handler code for notes section
- added db code for notes section
- supports only get all notes at the moment
- add sql for notes section
- add profile api call in main profile page
- add transform to notes and update sql
- add ux for adding a new note
- add ui for adding a note
- add redux action to post / put an item
- add integration with backend support for notes section
Notes section uses redux actions to get all notes, update a single note
or delete a single note. we can also add a new note.
=> Add backend support for notes section

Makefile, apilayer/README.md, apilayer/handler/EventsHandler.go, apilayer/handler/NotificationHandler.go, apilayer/handler/ProfileHandler.go, apilayer/handler/UserHandler.go, apilayer/main.go, apilayer/model/Event.go, apilayer/model/Notification.go, apilayer/model/Profile.go, apilayer/model/User.go, apilayer/swagger.yaml
Added swagger docs to the api layer. Run the swagger with make file
command. You have to serve the yaml file yourself atm. Its not hooked up
with any UI operation.
Users are able to view the swagger however interactions might be limited
since they are not served to a local platform.
closes https://github.com/earmuff-jam/mashed/issues/96
=> Adding swagger docs to the project

Makefile, apilayer/dataLake/hoard/dataLake.go, apilayer/dataLake/main.go, apilayer/db/Eventsdb.go, apilayer/db/Profiledb.go, apilayer/go.mod, apilayer/go.sum
- add script to load test data.
- use faker to generate data to ingest in the application
- update datagen to support loading both testdata.sql and generated data
- update expense rows to support test data scripts
closes #77
=> Add test data scripts for ease of use

frontend/src/Components/Notes/NotesDetails.jsx, frontend/src/Components/ProfileNavigationMenu/ProfileNavigationMenu.jsx, frontend/src/Components/ViewExpenseList/ViewExpenseList.jsx, frontend/src/stories/CreateNewEvent/CreateNewEvent.jsx
Adds ability to directly navigate users to rough notes section. uses navigate with state function. upon refresh users are redirected back to regular workflow.
closes #121
=> Add ability to directly navigate to notes section

apilayer/db/Inventorydb.go, apilayer/handler/InventoriesHandler.go, apilayer/handler/InventoriesHandler_test.go, apilayer/handler/NotesHandler_test.go, apilayer/handler/ProfileHandler_test.go, apilayer/main.go, frontend/src/Components/DrawerListComponent/List.jsx, frontend/src/Components/Inventory/Inventories.jsx, frontend/src/Components/ItemDetail/ViewItemDetail.jsx, frontend/src/Components/ViewExpenseList/ViewExpenseList.jsx, frontend/src/Containers/Profile/profileSaga.js, frontend/src/Containers/Profile/profileSlice.js, setup/devscript/test_data.sql
- update api layer code to support array of ids
- updated unit tests
- added icon btn to inventory sheet to delete selected inventories
- remove icon from view expense list and view item list
closes #113
=> Add ability to remove inventories

frontend/src/features/Layout/Layout.jsx, frontend/src/features/Layout/MenuActionBar.jsx
- add drawer for navigation bar.
- hide navigation bar after single click i had to add a timeout because of how the drawer was conflicting with the navigation commands.
Closes #187
=> 187 - Add drawer for navigation bar

frontend/src/features/LandingPage/Contact/Contact.jsx, frontend/src/features/LandingPage/Contact/ContactUsForm.jsx, frontend/src/features/LandingPage/LandingPage.jsx, frontend/src/features/LandingPage/Pricing/ItemWrapper.jsx, frontend/src/features/LandingPage/Pricing/Pricing.jsx, frontend/src/features/Layout/Layout.jsx, frontend/src/util/Theme.js
Adds pricing and contact us information for the landing page.
=> 212 Update landing page with pricing and contact us information

apilayer/dataLake/hoard/dataLake.go, apilayer/db/Categoriesdb.go, apilayer/db/MaintenancePlandb.go, apilayer/handler/AssetSummaryHandler_test.go, apilayer/handler/CategoriesHandler_test.go, apilayer/handler/InventoriesHandler_test.go, apilayer/handler/MaintenancePlan_test.go, apilayer/handler/NotesHandler_test.go, apilayer/handler/ProfileHandler_test.go, apilayer/handler/RecentActivities_test.go, apilayer/handler/Statuses_test.go, apilayer/handler/UserHandler_test.go, frontend/src/features/Categories/Category.jsx, frontend/src/features/Categories/CategoryList.jsx, frontend/src/features/Categories/categoriesSlice.js, frontend/src/features/Maintenance/PlanList.jsx, frontend/src/features/Maintenance/maintenanceSaga.js, frontend/src/features/Maintenance/maintenanceSlice.js, frontend/src/features/Profile/profileSlice.js, frontend/src/features/RecentList/RecentActivities.jsx, frontend/src/features/Reports/Reports.jsx, frontend/src/features/common/ItemCard/ItemCard.jsx, frontend/src/features/common/SharableGroups.jsx, setup/deployment_guide.md, setup/dev-notes.md, setup/devscript/test_data.sql
- Added support to share categories and maintenance plans with other users.
- Updated code to support empty values in data. after creating a new user, we realized
that there is couple of tech debt to clear and close. added support for that as well.
- Created new Autocomplete component to support adding new users as collaborators in the group.
- Updated test files to support new admin user / password combo
- Added new SharableGroups component
- Updated test case to support retaining email_address after change in ProfileHandler_test file.
- Updated maintenance plan and fix bug
- Updated maintenance plan api and ui to support sharing of items.
- Fixed bug with ItemCard component where the autocomplete was not displaying
the selected emails. the fix was to use isOptionEqualToValue function …
=> 183 share category

apilayer/dataLake/hoard/dataLake.go, apilayer/db/Userdb.go, apilayer/handler/UserHandler.go, apilayer/handler/UserHandler_test.go, apilayer/main.go, apilayer/model/User.go, frontend/src/features/LandingPage/Signup.jsx, frontend/src/features/LandingPage/authSaga.js, frontend/src/features/LandingPage/authSlice.js, frontend/src/features/LandingPage/constants.jsx, server/migrations/0004_create_auth_users_table_community.up.sql, server/migrations/0006_create_profiles_table_community.up.sql, setup/devscript/test_data.sql
[233 Add user validation during sign up](https://github.com/earmuff-jam/assetalert/pull/237/commits/8977040966455abae1d20a7397caca767efc6a49)
- added ability to create username during signup process
- added service layer to validate user email if they exist
- added unit test to support validation of user email
- addded model and perform tech debt cleanup
- added user model for user.go
- updated redux actions and saga for validation of user email address
- updated ui component to structure the check mark vs cross mark for valid user in the ui
closes https://github.com/earmuff-jam/assetalert/issues/233
=> 233 Added username during signup

apilayer/handler/AssetSummaryHandler.go, apilayer/handler/CategoriesHandler.go, apilayer/handler/FileServerHandler.go, apilayer/handler/InventoriesHandler.go, apilayer/handler/MaintenancePlan.go, apilayer/handler/NotesHandler.go, apilayer/handler/ProfileHandler.go, apilayer/handler/Statuses.go, apilayer/handler/StorageLocationHandler.go, apilayer/handler/UserHandler.go, apilayer/swagger.yaml
- Add proper categorization of apis.
=> 238 - Update swagger spec

apilayer/db/Reportdb.go, apilayer/handler/ReportHandler.go, apilayer/handler/ReportHandler_test.go, apilayer/main.go, apilayer/model/Report.go, frontend/src/Store.js, frontend/src/features/Reports/FilterMenu.jsx, frontend/src/features/Reports/Reports.jsx, frontend/src/features/Reports/constants.jsx, frontend/src/features/Reports/reportSaga.js, frontend/src/features/Reports/reportSlice.js, setup/devscript/test_data.sql
[206 Added api to generate reports](https://github.com/earmuff-jam/assetalert/pull/232/commits/fc6bd7d39d84ab393952794e2fdba8ad04090c93)
- created new report model
- created db layer for report
- created ReportHandler to support handler logic for reports
- created redux and saga actions
- created FilterMenu.jsx file to support filtering of items
- updated reports.jsx component
- created reportSlice and reportSaga files to support redux actions
- updated Store.js to support new redux actions
- updated the sql logic to support overdue items. reports api returns
result that have been updated after that selected start date, or returns if the
item is overdue after that selected start date.
closes https://github.com/earmuff-jam/assetalert/issues/206
=> 206 add custom filters

frontend/src/features/Categories/CategoryList.jsx, frontend/src/features/Categories/categoriesSaga.js, frontend/src/features/Categories/categoriesSlice.js, frontend/src/features/Maintenance/Plan.jsx, frontend/src/features/Maintenance/maintenanceSaga.js, frontend/src/features/Maintenance/maintenanceSlice.js
- Added export functionality for categories and maintenance plans
=> 244 - Added ability to export

.vscode/launch.json, apilayer/dataLake/hoard/dataLake.go, apilayer/db/Inventorydb.go, apilayer/db/Reportdb.go, apilayer/handler/InventoriesHandler.go, frontend/src/features/Categories/Category.jsx, frontend/src/features/Categories/CategoryItem.jsx, frontend/src/features/Categories/CategoryList.jsx, frontend/src/features/InventoryList/inventorySaga.js, frontend/src/features/Maintenance/MaintenanceItem.jsx, frontend/src/features/Maintenance/PlanList.jsx, frontend/src/features/Reports/FilterMenu.jsx, frontend/src/features/Reports/Reports.jsx, frontend/src/features/Reports/constants.jsx, frontend/src/features/common/ItemCard/DetailsCard.jsx, frontend/src/features/common/ItemCard/ItemCard.jsx
[208 - Added reports functionality](https://github.com/earmuff-jam/assetalert/pull/246/commits/16f0d2bda3a0bf74dfe266f0e29467694a995151)
- updated categories and maintenance plan to use combined components
- updated lauch.json file to debug data lake
- updated limit on data lake for each functions
- added since date time for asset lists created by the selected user
- updated inventorydb.go and reportsdb.go file to accomodate query params
- created DetailsCard.jsx component for list of categories and maintenance plans
- updated inventory saga to support params
- updated reports and filter menu to support displaying of selected data. YTD is selected as
default for the reports page when the user lands on the page.
closes https://github.com/earmuff-jam/assetalert/issues/208
=> Refactor categories and Maintenance plans

apilayer/db/Categoriesdb.go, apilayer/db/Notedb.go, apilayer/model/Category.go, frontend/src/features/Categories/AddCategory.jsx, frontend/src/features/Categories/Category.jsx, frontend/src/features/Categories/categoriesSaga.js, frontend/src/features/Maintenance/AddPlan.jsx, frontend/src/features/Maintenance/PlanList.jsx, frontend/src/features/Maintenance/maintenanceSaga.js, frontend/src/features/Notes/AddNote.jsx, frontend/src/features/Notes/NotesDetails.jsx, frontend/src/features/common/Location/LocationPicker.jsx, server/migrations/0025_update_categories_table_community.up.sql
Added ability to edit selected location
- added ability to change location for the selected location picker.
- added a new ref and a handler that listens to the click and returns the lat, lon of the selected location. this allowed us to change the location from the map.
i think we should kind of enlarge the map a little bit since it is now difficult to traverse around the map and if we add features to this map later on, we run the risk of having too much stuff on a simple box.
Added location picker for Categories
- added location picker for categories component
- added new sql to add new column for categories component
Support multiple rows
- added support to display multiple categories and maintenance plans. the current limit is at 100, if the user creates / has more items that 100, we …
=> 178 - Updated location picker component

frontend/src/features/Reports/Reports.jsx, frontend/src/features/Reports/reportSlice.js
- added changes to support variations of reports during downloading them. currently we are supporting csv download, but it should be refined later on, since we are also not sure how this report is being / will be used in the future.
=> updated download reports

frontend/.storybook/main.js, frontend/jsconfig.json, frontend/src/common/utils.jsx, frontend/src/features/Notes/AddNote/AddNoteHeader.jsx, frontend/src/features/Notes/AddNote/AddNoteHeader.stories.js, frontend/src/features/Notes/AddNote/AddNoteLocationPicker.jsx, frontend/src/features/Notes/AddNote/AddNoteLocationPicker.stories.js, frontend/src/features/Notes/AddNote/AddNoteStatusOptions.jsx, frontend/src/features/Notes/AddNote/AddNotesStatusOptions.stories.js, frontend/src/features/Notes/Header/NoteHeader.jsx, frontend/src/features/Notes/Header/NoteHeader.stories.js, frontend/src/features/Notes/Note/Note.jsx, frontend/src/features/Notes/Note/Note.stories.js, frontend/src/features/Notes/NoteAccordion/NoteAccordionDetails.jsx, frontend/src/features/Notes/NoteAccordion/NoteAccordionDetails.stories.js, frontend/src/features/Notes/NoteAccordion/NoteAccordionSummary.jsx, frontend/src/features/Notes/NoteAccordion/NoteAccordionSummary.stories.js, frontend/src/features/Notes/NotesList.jsx, frontend/src/features/Notes/constants.jsx, frontend/vite.config.js
- Adds the ability to update files with @ from jsconfig.js and vite.config
- Adds empty Notes.stories.js file
- Added ability to populate stories in storybook
- Added storybook content for notes section
- Adds storybook for notes component folders
- Tech debt cleanup for notes section and update constants
closes https://github.com/earmuff-jam/pulse/issues/282
=> 282 - Update Note storybook component

frontend/src/features/Reports/ReportCard/ReportCardWrapper.jsx, frontend/src/features/Reports/ReportCard/ReportCardWrapper.stories.js, frontend/src/features/Reports/ReportContent/ReportContent.jsx, frontend/src/features/Reports/ReportContent/ReportContent.stories.js, frontend/src/features/Reports/ReportHeader/ReportsHeader.jsx, frontend/src/features/Reports/ReportHeader/ReportsHeader.stories.js, frontend/src/features/Reports/ReportItemDetails/ReportItemDetails.jsx, frontend/src/features/Reports/ReportItemDetails/ReportItemDetails.stories.js, frontend/src/features/Reports/Reports.jsx, frontend/src/features/Reports/ReportsFilterMenu/ReportsFilterMenu.jsx, frontend/src/features/Reports/ReportsFilterMenu/ReportsFilterMenu.stories.js
- Added storybook to reports page
- Seperated components in its own sub folders inside reports
Closes #288
=> 288 - Added storybook to reports page

apilayer/bucket/readWrite.go, apilayer/db/Imagedb.go, apilayer/handler/ImageHandler.go, frontend/src/common/Chart/BarChart.jsx, frontend/src/common/DataTable/CustomTableComponent/CustomTableBody/CustomTableBody.jsx, frontend/src/common/DataTable/CustomTableComponent/CustomTableHeader/CustomTableHeader.jsx, frontend/src/common/DataTable/CustomTableComponent/TableComponent.jsx, frontend/src/features/CategoryItemDetails/CategoryItemDetailsAddAsset/CategoryItemDetailsAddAsset.jsx, frontend/src/features/CategoryItemDetails/CategoryItemDetailsContent/CategoryItemDetailsDataTable.jsx, frontend/src/features/CategoryItemDetails/CategoryItemDetailsContent/CategoryItemDetailsGraph.jsx, frontend/src/features/CategoryItemDetails/categoryItemDetailsSaga.js, frontend/src/features/InventoryList/InventoryList.jsx, frontend/src/features/MaintenancePlanItemDetails/MaintenancePlanItemDetails.jsx, frontend/src/features/MaintenancePlanItemDetails/MaintenancePlanItemDetailsAddAsset/MaintenancePlanItemDetailsAddAsset.jsx, frontend/src/features/MaintenancePlanItemDetails/MaintenancePlanItemDetailsAddAsset/MaintenancePlanItemDetailsAddAsset.stories.js, frontend/src/features/MaintenancePlanItemDetails/MaintenancePlanItemDetailsContent/MaintenancePlanItemDetailsContent.jsx, frontend/src/features/MaintenancePlanItemDetails/MaintenancePlanItemDetailsContent/MaintenancePlanItemDetailsContent.stories.js, frontend/src/features/MaintenancePlanItemDetails/MaintenancePlanItemDetailsContent/MaintenancePlanItemDetailsGraph.jsx, frontend/src/features/MaintenancePlanItemDetails/MaintenancePlanItemDetailsContent/MaintenancePlanItemDetailsGraph.stories.js, frontend/src/features/MaintenancePlanItemDetails/MaintenancePlanItemDetailsContent/MaintenancePlanItemDetailsGraphContent.jsx, frontend/src/features/MaintenancePlanItemDetails/MaintenancePlanItemDetailsContent/MaintenancePlanItemDetailsGraphContent.stories.js, frontend/src/features/MaintenancePlanItemDetails/MaintenancePlanItemDetailsHeader/MaintenancePlanItemDetailsHeader.jsx, frontend/src/features/MaintenancePlanItemDetails/MaintenancePlanItemDetailsHeader/MaintenancePlanItemDetailsHeader.stories.js, frontend/src/features/MaintenancePlanItemDetails/maintenancePlanItemSaga.js, frontend/src/features/MaintenancePlanItemDetails/maintenancePlanItemSlice.js
- Updated maintenance item component to use storybook.
- Created storybook for all other respective components.
- Updated styles for BarChart.jsx file.
Added background color to match the theme for item association graph and removed border so that it looks flush with the theme.
Closes #289
=> 289 - Added storybook for maintenance item

frontend/src/common/Chart/PieChart.jsx, frontend/src/features/Assets/AddAssetFormDetails/AddAssetActionButtons.stories.js, frontend/src/features/Assets/AddAssetFormDetails/AddAssetFormDetails.jsx, frontend/src/features/Assets/AddAssetFormDetails/AddAssetFormDetails.stories.js, frontend/src/features/Assets/AddAssetFormDetails/AddAssetFormInstructions.stories.js, frontend/src/features/Assets/AddAssetFormDetails/AddAssetFormItemDetails.jsx, frontend/src/features/Assets/AddAssetFormDetails/AddAssetFormItemDetails.stories.js, frontend/src/features/Assets/AddAssetFormDetails/AddAssetFormReview.jsx, frontend/src/features/Assets/AddAssetFormDetails/AddAssetFormReview.stories.js, frontend/src/features/Assets/AddAssetFormDetails/AddAssetFormSelection.jsx, frontend/src/features/Assets/AddAssetFormDetails/AddAssetFormSelection.stories.js, frontend/src/features/Assets/AddAssetFormDetails/AddAssetSteps.stories.js, frontend/src/features/Assets/AddAssetsInBulk/AddAssetsInBulk.stories.js, frontend/src/features/Assets/AddAssetsInBulk/AddAssetsInBulkContent.stories.js, frontend/src/features/Assets/AddAssetsInBulk/AddAssetsInBulkHeader.stories.js, frontend/src/features/Assets/AssetDetailsDrawer/AssetDetailsDrawer.stories.js, frontend/src/features/Assets/AssetDetailsDrawer/AssetDetailsDrawerContent.stories.js, frontend/src/features/Assets/AssetDetailsDrawer/AssetDetailsDrawerHeader.stories.js, frontend/src/features/Home/OverviewContent/OverviewContentAssetGraph.jsx, frontend/src/features/MaintenancePlanItemDetails/MaintenancePlanItemDetailsContent/MaintenancePlanItemDetailsGraphContent.jsx, frontend/src/features/SelectedAsset/SelectedAssetFormFields.stories.js, frontend/src/features/SelectedAsset/SelectedAssetMoreInformation.jsx, frontend/src/features/SelectedAsset/SelectedAssetMoreInformation.stories.js, frontend/src/features/SelectedAsset/SelectedAssetMoreInformationCheckbox.jsx, frontend/src/features/SelectedAsset/SelectedAssetMoreInformationCheckbox.stories.js, frontend/src/features/SelectedAsset/SelectedAssetReturnInformationContent.stories.js, frontend/src/features/SelectedAsset/SelectedAssetWeightDimension.stories.js
Added storybook for asset details page including the add asset details section. Added new form components, renamed a couple of them and added more details to the asset page.
closes #294
=> 294 Updated storybook for asset details

apilayer/db/Profiledb.go, apilayer/handler/ProfileHandler.go, apilayer/handler/ProfileHandler_test.go, apilayer/main.go, apilayer/model/Profile.go, frontend/src/features/Profile/ProfilePage.jsx, frontend/src/features/Profile/UserStatus/UserStatus.jsx, frontend/src/features/Profile/profileSaga.js, frontend/src/features/Profile/profileSlice.js
Update ability to view user profile stats that
displays the list of categories and maintenance plan. It should also display the count of asset list.
Closes #206
=> 206 Update profile stats

frontend/src/features/Layout/constants.jsx, frontend/src/features/Notes/Note/Note.jsx, frontend/src/features/Notes/NoteAccordion/NoteAccordionDetails.jsx, setup/dev/test_data.sql
Updated Notes UI component
- Updated notes component to open Recently Added Notes by default. Also updated code to support display of location if the selected note has location details and the user screen is higher than small screen size.
- Update the title to Notes from Personal Notes in MenuActionBar.jsx file to remove redundant code for Notes section. Also updated test data so that we get some real data to test the application / feature with.
Closes #320
=> 320 Update Notes

apilayer/db/Profiledb.go, frontend/src/features/Home/Overview.jsx, frontend/src/features/Home/OverviewContent/OverviewContentAssetGraph.jsx, frontend/src/features/Home/constants.js, frontend/src/features/LandingPage/Authentication/Signup/Signup.jsx, frontend/src/features/LandingPage/Authentication/Signup/SignupFormFields.jsx, frontend/src/features/LandingPage/Authentication/Signup/SignupHelperText.jsx, frontend/src/features/LandingPage/Authentication/Signup/SignupHelperText.stories.js
Fixes profile stats as the details were incorrect in the request / response pair.
During signup, even though the email address is not valid / unique, we
were seeing issues where the user could attempt to register even though
they did not have the required permissions. Fixed this issue.
Created new helper text component and storybook for the helper text
component
Closes #339
=> 339 - Fixed profile stats
